name: CI
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: 8.1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_FILES_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run php-cs-fixer
        run: bin/php-cs-fixer fix --verbose --diff --dry-run

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: 8.1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_FILES_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: bin/phpstan
